# Generated by Django 6.1.1 on 2026-10-02 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('temporada', models.CharField(blank=True, max_length=30)),
                ('imagen_url', models.URLField(blank=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'colección',
                'verbose_name_plural': 'colecciones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('detalle', models.CharField(blank=True, max_length=180)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('imagen_url', models.URLField(blank=True)),
                ('destacado', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('coleccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='core.coleccion')),
            ],
            options={
                'ordering': ['-destacado', 'nombre'],
            },
        ),
    ]
