# Generated by Django 6.1.1 on 2026-10-02 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coleccion',
            options={'ordering': ('nombre',), 'verbose_name': 'colección', 'verbose_name_plural': 'colecciones'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ('-destacado', 'nombre')},
        ),
    ]
