# Generated by Django 6.1.1 on 2026-09-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Impuesto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Ej: IVA 19%", max_length=50, unique=True
                    ),
                ),
                (
                    "tasa",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Porcentaje, ej: 19.00",
                        max_digits=5,
                    ),
                ),
                (
                    "vigente",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si el impuesto aplica actualmente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Impuesto",
                "verbose_name_plural": "Impuestos",
            },
        ),
    ]
