# Generated by Django 6.1.1 on 2026-09-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuracion", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Moneda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo_iso",
                    models.CharField(
                        help_text="Código ISO 4217. Ej: COP, USD, EUR",
                        max_length=3,
                        unique=True,
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre completo. Ej: Peso colombiano", max_length=50
                    ),
                ),
                (
                    "simbolo",
                    models.CharField(help_text="Símbolo. Ej: $, €, £", max_length=5),
                ),
                (
                    "tasa_cambio",
                    models.DecimalField(
                        decimal_places=4,
                        default=1.0,
                        help_text="Tasa respecto a la moneda principal. La principal siempre vale 1.",
                        max_digits=12,
                    ),
                ),
                (
                    "es_principal",
                    models.BooleanField(
                        default=False,
                        help_text="Solo puede haber una moneda principal activa a la vez.",
                    ),
                ),
                (
                    "activa",
                    models.BooleanField(
                        default=True,
                        help_text="Monedas inactivas no se ofrecen al usuario.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Moneda",
                "verbose_name_plural": "Monedas",
                "ordering": ["-es_principal", "codigo_iso"],
            },
        ),
    ]
