# Generated by Django 6.1.1 on 2026-10-01 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0002_moneda'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código de idioma. Ej: es, en, fr, pt', max_length=10, unique=True)),
                ('nombre', models.CharField(help_text='Nombre descriptivo del idioma. Ej: Español, English', max_length=50)),
                ('es_principal', models.BooleanField(default=False, help_text='Solo puede haber un idioma principal por defecto a la vez.')),
                ('activo', models.BooleanField(default=True, help_text='Idiomas inactivos no se ofrecen al usuario.')),
            ],
            options={
                'verbose_name': 'Idioma',
                'verbose_name_plural': 'Idiomas',
                'ordering': ['-es_principal', 'codigo'],
            },
        ),
    ]
