# Generated by Django 6.1.1 on 2026-10-01 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0003_idioma'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametroGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tienda', models.CharField(default='Oro del Sol', help_text='Nombre comercial de la joyería', max_length=100)),
                ('lema', models.CharField(blank=True, default='Joyería exclusiva en anillos de oro de 18K', help_text='Lema o eslogan de la marca', max_length=200)),
                ('nit', models.CharField(default='900.123.456-7', help_text='Identificación tributaria (NIT/RUT)', max_length=30)),
                ('correo_contacto', models.EmailField(default='contacto@orodelsol.com', help_text='Correo electrónico de contacto y atención', max_length=254)),
                ('telefono_contacto', models.CharField(default='+57 300 123 4567', help_text='Número telefónico / WhatsApp de atención', max_length=30)),
                ('direccion', models.CharField(default='Calle de la Joyería # 18K-01', help_text='Dirección física del showroom o taller', max_length=200)),
                ('ciudad', models.CharField(default='Bogotá, Colombia', help_text='Ciudad y país sede', max_length=100)),
                ('horario_atencion', models.CharField(blank=True, default='Lunes a Sábado: 9:00 AM - 7:00 PM', help_text='Horarios de atención al público', max_length=150)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parametros_actualizados', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Parámetro General',
                'verbose_name_plural': 'Parámetros Generales',
            },
        ),
    ]
