# Generated by Django 6.1.1 on 2026-09-23 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_foto_usuario_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/', verbose_name='Foto de perfil'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(max_length=15, verbose_name='Teléfono'),
        ),
    ]
